AllCops:
  TargetRubyVersion: 2.6

Style/PerlBackrefs:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false